2022-09-29 08:54:01,580 - exc_logger - ERROR - exception in divideByZero
=============
Traceback (most recent call last):
  File "/Users/sahil/Desktop/Study/PythonTips/11-SOLID/betterpython-main/7 - dealing with errors/advanced/logging-decorator.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/Users/sahil/Desktop/Study/PythonTips/11-SOLID/betterpython-main/7 - dealing with errors/advanced/logging-decorator.py", line 47, in divideByZero
    return 12/0
ZeroDivisionError: division by zero
